/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.api;

import com.datengaertnerei.jira.rest.client.ApiException;
import com.datengaertnerei.jira.rest.client.model.Resolution;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IssueResolutionsApi
 */
@Ignore
public class IssueResolutionsApiTest {

    private final IssueResolutionsApi api = new IssueResolutionsApi();

    
    /**
     * Get resolution
     *
     * Returns an issue resolution value.  **[Permissions](#permissions) required:** Permission to access Jira.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResolutionTest() throws ApiException {
        String id = null;
        Resolution response = api.getResolution(id);

        // TODO: test validations
    }
    
    /**
     * Get resolutions
     *
     * Returns a list of all issue resolution values.  **[Permissions](#permissions) required:** Permission to access Jira.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResolutionsTest() throws ApiException {
        List<Resolution> response = api.getResolutions();

        // TODO: test validations
    }
    
}
