/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Details of an operation to perform on a field.
 */
@ApiModel(description = "Details of an operation to perform on a field.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-17T17:45:56.601554Z[Etc/UTC]")
public class FieldUpdateOperation {
  public static final String SERIALIZED_NAME_ADD = "add";
  @SerializedName(SERIALIZED_NAME_ADD)
  private Object add = null;

  public static final String SERIALIZED_NAME_SET = "set";
  @SerializedName(SERIALIZED_NAME_SET)
  private Object set = null;

  public static final String SERIALIZED_NAME_REMOVE = "remove";
  @SerializedName(SERIALIZED_NAME_REMOVE)
  private Object remove = null;

  public static final String SERIALIZED_NAME_EDIT = "edit";
  @SerializedName(SERIALIZED_NAME_EDIT)
  private Object edit = null;


  public FieldUpdateOperation add(Object add) {
    
    this.add = add;
    return this;
  }

   /**
   * A map containing the name of a field and the value to add to it.
   * @return add
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"labels\":\"Training\",\"issuelinks\":{\"id\":10001}}", value = "A map containing the name of a field and the value to add to it.")

  public Object getAdd() {
    return add;
  }


  public void setAdd(Object add) {
    this.add = add;
  }


  public FieldUpdateOperation set(Object set) {
    
    this.set = set;
    return this;
  }

   /**
   * A map containing the name of a field and the value to set in it.
   * @return set
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"summary\":\"A new summary\",\"issuetype\":{\"id\":10010}}", value = "A map containing the name of a field and the value to set in it.")

  public Object getSet() {
    return set;
  }


  public void setSet(Object set) {
    this.set = set;
  }


  public FieldUpdateOperation remove(Object remove) {
    
    this.remove = remove;
    return this;
  }

   /**
   * A map containing the name of a field and the value to removed from it.
   * @return remove
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"labels\":\"Training\",\"components\":{\"id\":10017}}", value = "A map containing the name of a field and the value to removed from it.")

  public Object getRemove() {
    return remove;
  }


  public void setRemove(Object remove) {
    this.remove = remove;
  }


  public FieldUpdateOperation edit(Object edit) {
    
    this.edit = edit;
    return this;
  }

   /**
   * A map containing the name of a field and the value to edit in it.
   * @return edit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"timetracking\":{\"key\":\"JIRA\"}}", value = "A map containing the name of a field and the value to edit in it.")

  public Object getEdit() {
    return edit;
  }


  public void setEdit(Object edit) {
    this.edit = edit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldUpdateOperation fieldUpdateOperation = (FieldUpdateOperation) o;
    return Objects.equals(this.add, fieldUpdateOperation.add) &&
        Objects.equals(this.set, fieldUpdateOperation.set) &&
        Objects.equals(this.remove, fieldUpdateOperation.remove) &&
        Objects.equals(this.edit, fieldUpdateOperation.edit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, set, remove, edit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldUpdateOperation {\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("    edit: ").append(toIndentedString(edit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

