/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.datengaertnerei.jira.rest.client.model.FoundGroup;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The list of groups found in a search, including header text (Showing X of Y matching groups) and total of matched groups.
 */
@ApiModel(description = "The list of groups found in a search, including header text (Showing X of Y matching groups) and total of matched groups.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-17T17:45:56.601554Z[Etc/UTC]")
public class FoundGroups {
  public static final String SERIALIZED_NAME_HEADER = "header";
  @SerializedName(SERIALIZED_NAME_HEADER)
  private String header;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public static final String SERIALIZED_NAME_GROUPS = "groups";
  @SerializedName(SERIALIZED_NAME_GROUPS)
  private List<FoundGroup> groups = null;


  public FoundGroups header(String header) {
    
    this.header = header;
    return this;
  }

   /**
   * Header text indicating the number of groups in the response and the total number of groups found in the search.
   * @return header
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Header text indicating the number of groups in the response and the total number of groups found in the search.")

  public String getHeader() {
    return header;
  }


  public void setHeader(String header) {
    this.header = header;
  }


  public FoundGroups total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * The total number of groups found in the search.
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total number of groups found in the search.")

  public Integer getTotal() {
    return total;
  }


  public void setTotal(Integer total) {
    this.total = total;
  }


  public FoundGroups groups(List<FoundGroup> groups) {
    
    this.groups = groups;
    return this;
  }

  public FoundGroups addGroupsItem(FoundGroup groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<FoundGroup> getGroups() {
    return groups;
  }


  public void setGroups(List<FoundGroup> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FoundGroups foundGroups = (FoundGroups) o;
    return Objects.equals(this.header, foundGroups.header) &&
        Objects.equals(this.total, foundGroups.total) &&
        Objects.equals(this.groups, foundGroups.groups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, total, groups);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FoundGroups {\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

