/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.datengaertnerei.jira.rest.client.model.IncludedFields;
import com.datengaertnerei.jira.rest.client.model.IssueTransition;
import com.datengaertnerei.jira.rest.client.model.IssueUpdateMetadata;
import com.datengaertnerei.jira.rest.client.model.JsonTypeBean;
import com.datengaertnerei.jira.rest.client.model.Operations;
import com.datengaertnerei.jira.rest.client.model.PageOfChangelogs;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * IssueBean
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-17T17:45:56.601554Z[Etc/UTC]")
public class IssueBean {
  public static final String SERIALIZED_NAME_EXPAND = "expand";
  @SerializedName(SERIALIZED_NAME_EXPAND)
  private String expand;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  private URI self;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_RENDERED_FIELDS = "renderedFields";
  @SerializedName(SERIALIZED_NAME_RENDERED_FIELDS)
  private Map<String, Object> renderedFields = null;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Map<String, Object> properties = null;

  public static final String SERIALIZED_NAME_NAMES = "names";
  @SerializedName(SERIALIZED_NAME_NAMES)
  private Map<String, String> names = null;

  public static final String SERIALIZED_NAME_SCHEMA = "schema";
  @SerializedName(SERIALIZED_NAME_SCHEMA)
  private Map<String, JsonTypeBean> schema = null;

  public static final String SERIALIZED_NAME_TRANSITIONS = "transitions";
  @SerializedName(SERIALIZED_NAME_TRANSITIONS)
  private List<IssueTransition> transitions = null;

  public static final String SERIALIZED_NAME_OPERATIONS = "operations";
  @SerializedName(SERIALIZED_NAME_OPERATIONS)
  private Operations operations;

  public static final String SERIALIZED_NAME_EDITMETA = "editmeta";
  @SerializedName(SERIALIZED_NAME_EDITMETA)
  private IssueUpdateMetadata editmeta;

  public static final String SERIALIZED_NAME_CHANGELOG = "changelog";
  @SerializedName(SERIALIZED_NAME_CHANGELOG)
  private PageOfChangelogs changelog;

  public static final String SERIALIZED_NAME_VERSIONED_REPRESENTATIONS = "versionedRepresentations";
  @SerializedName(SERIALIZED_NAME_VERSIONED_REPRESENTATIONS)
  private Map<String, Map<String, Object>> versionedRepresentations = null;

  public static final String SERIALIZED_NAME_FIELDS_TO_INCLUDE = "fieldsToInclude";
  @SerializedName(SERIALIZED_NAME_FIELDS_TO_INCLUDE)
  private IncludedFields fieldsToInclude;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private Map<String, Object> fields = null;


   /**
   * Expand options that include additional issue details in the response.
   * @return expand
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Expand options that include additional issue details in the response.")

  public String getExpand() {
    return expand;
  }




   /**
   * The ID of the issue.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the issue.")

  public String getId() {
    return id;
  }




   /**
   * The URL of the issue details.
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL of the issue details.")

  public URI getSelf() {
    return self;
  }




   /**
   * The key of the issue.
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The key of the issue.")

  public String getKey() {
    return key;
  }




   /**
   * The rendered value of each field present on the issue.
   * @return renderedFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The rendered value of each field present on the issue.")

  public Map<String, Object> getRenderedFields() {
    return renderedFields;
  }




   /**
   * Details of the issue properties identified in the request.
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details of the issue properties identified in the request.")

  public Map<String, Object> getProperties() {
    return properties;
  }




   /**
   * The ID and name of each field present on the issue.
   * @return names
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID and name of each field present on the issue.")

  public Map<String, String> getNames() {
    return names;
  }




   /**
   * The schema describing each field present on the issue.
   * @return schema
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The schema describing each field present on the issue.")

  public Map<String, JsonTypeBean> getSchema() {
    return schema;
  }




   /**
   * The transitions that can be performed on the issue.
   * @return transitions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The transitions that can be performed on the issue.")

  public List<IssueTransition> getTransitions() {
    return transitions;
  }




   /**
   * The operations that can be performed on the issue.
   * @return operations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The operations that can be performed on the issue.")

  public Operations getOperations() {
    return operations;
  }




   /**
   * The metadata for the fields on the issue that can be amended.
   * @return editmeta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The metadata for the fields on the issue that can be amended.")

  public IssueUpdateMetadata getEditmeta() {
    return editmeta;
  }




   /**
   * Details of changelogs associated with the issue.
   * @return changelog
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details of changelogs associated with the issue.")

  public PageOfChangelogs getChangelog() {
    return changelog;
  }




   /**
   * The versions of each field on the issue.
   * @return versionedRepresentations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The versions of each field on the issue.")

  public Map<String, Map<String, Object>> getVersionedRepresentations() {
    return versionedRepresentations;
  }




  public IssueBean fieldsToInclude(IncludedFields fieldsToInclude) {
    
    this.fieldsToInclude = fieldsToInclude;
    return this;
  }

   /**
   * Get fieldsToInclude
   * @return fieldsToInclude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IncludedFields getFieldsToInclude() {
    return fieldsToInclude;
  }


  public void setFieldsToInclude(IncludedFields fieldsToInclude) {
    this.fieldsToInclude = fieldsToInclude;
  }


  public IssueBean fields(Map<String, Object> fields) {
    
    this.fields = fields;
    return this;
  }

  public IssueBean putFieldsItem(String key, Object fieldsItem) {
    if (this.fields == null) {
      this.fields = new HashMap<>();
    }
    this.fields.put(key, fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, Object> getFields() {
    return fields;
  }


  public void setFields(Map<String, Object> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueBean issueBean = (IssueBean) o;
    return Objects.equals(this.expand, issueBean.expand) &&
        Objects.equals(this.id, issueBean.id) &&
        Objects.equals(this.self, issueBean.self) &&
        Objects.equals(this.key, issueBean.key) &&
        Objects.equals(this.renderedFields, issueBean.renderedFields) &&
        Objects.equals(this.properties, issueBean.properties) &&
        Objects.equals(this.names, issueBean.names) &&
        Objects.equals(this.schema, issueBean.schema) &&
        Objects.equals(this.transitions, issueBean.transitions) &&
        Objects.equals(this.operations, issueBean.operations) &&
        Objects.equals(this.editmeta, issueBean.editmeta) &&
        Objects.equals(this.changelog, issueBean.changelog) &&
        Objects.equals(this.versionedRepresentations, issueBean.versionedRepresentations) &&
        Objects.equals(this.fieldsToInclude, issueBean.fieldsToInclude) &&
        Objects.equals(this.fields, issueBean.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expand, id, self, key, renderedFields, properties, names, schema, transitions, operations, editmeta, changelog, versionedRepresentations, fieldsToInclude, fields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueBean {\n");
    sb.append("    expand: ").append(toIndentedString(expand)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    renderedFields: ").append(toIndentedString(renderedFields)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    transitions: ").append(toIndentedString(transitions)).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    editmeta: ").append(toIndentedString(editmeta)).append("\n");
    sb.append("    changelog: ").append(toIndentedString(changelog)).append("\n");
    sb.append("    versionedRepresentations: ").append(toIndentedString(versionedRepresentations)).append("\n");
    sb.append("    fieldsToInclude: ").append(toIndentedString(fieldsToInclude)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

