/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.datengaertnerei.jira.rest.client.model.FieldMetadata;
import com.datengaertnerei.jira.rest.client.model.StatusDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Details of an issue transition.
 */
@ApiModel(description = "Details of an issue transition.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-17T17:45:56.601554Z[Etc/UTC]")
public class IssueTransition extends HashMap<String, Object> {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private StatusDetails to;

  public static final String SERIALIZED_NAME_HAS_SCREEN = "hasScreen";
  @SerializedName(SERIALIZED_NAME_HAS_SCREEN)
  private Boolean hasScreen;

  public static final String SERIALIZED_NAME_IS_GLOBAL = "isGlobal";
  @SerializedName(SERIALIZED_NAME_IS_GLOBAL)
  private Boolean isGlobal;

  public static final String SERIALIZED_NAME_IS_INITIAL = "isInitial";
  @SerializedName(SERIALIZED_NAME_IS_INITIAL)
  private Boolean isInitial;

  public static final String SERIALIZED_NAME_IS_AVAILABLE = "isAvailable";
  @SerializedName(SERIALIZED_NAME_IS_AVAILABLE)
  private Boolean isAvailable;

  public static final String SERIALIZED_NAME_IS_CONDITIONAL = "isConditional";
  @SerializedName(SERIALIZED_NAME_IS_CONDITIONAL)
  private Boolean isConditional;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private Map<String, FieldMetadata> fields = null;

  public static final String SERIALIZED_NAME_EXPAND = "expand";
  @SerializedName(SERIALIZED_NAME_EXPAND)
  private String expand;

  public static final String SERIALIZED_NAME_LOOPED = "looped";
  @SerializedName(SERIALIZED_NAME_LOOPED)
  private Boolean looped;


  public IssueTransition id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the issue transition. Required when specifying a transition to undertake.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the issue transition. Required when specifying a transition to undertake.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


   /**
   * The name of the issue transition.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the issue transition.")

  public String getName() {
    return name;
  }




   /**
   * Details of the issue status after the transition.
   * @return to
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details of the issue status after the transition.")

  public StatusDetails getTo() {
    return to;
  }




   /**
   * Whether there is a screen associated with the issue transition.
   * @return hasScreen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether there is a screen associated with the issue transition.")

  public Boolean getHasScreen() {
    return hasScreen;
  }




   /**
   * Whether the issue transition is global, that is, the transition is applied to issues regardless of their status.
   * @return isGlobal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the issue transition is global, that is, the transition is applied to issues regardless of their status.")

  public Boolean getIsGlobal() {
    return isGlobal;
  }




   /**
   * Whether this is the initial issue transition for the workflow.
   * @return isInitial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether this is the initial issue transition for the workflow.")

  public Boolean getIsInitial() {
    return isInitial;
  }




   /**
   * Whether the transition is available to be performed.
   * @return isAvailable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the transition is available to be performed.")

  public Boolean getIsAvailable() {
    return isAvailable;
  }




   /**
   * Whether the issue has to meet criteria before the issue transition is applied.
   * @return isConditional
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the issue has to meet criteria before the issue transition is applied.")

  public Boolean getIsConditional() {
    return isConditional;
  }




   /**
   * Details of the fields associated with the issue transition screen. Use this information to populate &#x60;fields&#x60; and &#x60;update&#x60; in a transition request.
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details of the fields associated with the issue transition screen. Use this information to populate `fields` and `update` in a transition request.")

  public Map<String, FieldMetadata> getFields() {
    return fields;
  }




   /**
   * Expand options that include additional transition details in the response.
   * @return expand
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Expand options that include additional transition details in the response.")

  public String getExpand() {
    return expand;
  }




  public IssueTransition looped(Boolean looped) {
    
    this.looped = looped;
    return this;
  }

   /**
   * Get looped
   * @return looped
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getLooped() {
    return looped;
  }


  public void setLooped(Boolean looped) {
    this.looped = looped;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueTransition issueTransition = (IssueTransition) o;
    return Objects.equals(this.id, issueTransition.id) &&
        Objects.equals(this.name, issueTransition.name) &&
        Objects.equals(this.to, issueTransition.to) &&
        Objects.equals(this.hasScreen, issueTransition.hasScreen) &&
        Objects.equals(this.isGlobal, issueTransition.isGlobal) &&
        Objects.equals(this.isInitial, issueTransition.isInitial) &&
        Objects.equals(this.isAvailable, issueTransition.isAvailable) &&
        Objects.equals(this.isConditional, issueTransition.isConditional) &&
        Objects.equals(this.fields, issueTransition.fields) &&
        Objects.equals(this.expand, issueTransition.expand) &&
        Objects.equals(this.looped, issueTransition.looped) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, to, hasScreen, isGlobal, isInitial, isAvailable, isConditional, fields, expand, looped, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueTransition {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    hasScreen: ").append(toIndentedString(hasScreen)).append("\n");
    sb.append("    isGlobal: ").append(toIndentedString(isGlobal)).append("\n");
    sb.append("    isInitial: ").append(toIndentedString(isInitial)).append("\n");
    sb.append("    isAvailable: ").append(toIndentedString(isAvailable)).append("\n");
    sb.append("    isConditional: ").append(toIndentedString(isConditional)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    expand: ").append(toIndentedString(expand)).append("\n");
    sb.append("    looped: ").append(toIndentedString(looped)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

