/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ID of a registered webhook or error messages explaining why a webhook wasn&#39;t registered.
 */
@ApiModel(description = "ID of a registered webhook or error messages explaining why a webhook wasn't registered.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-17T17:45:56.601554Z[Etc/UTC]")
public class RegisteredWebhook {
  public static final String SERIALIZED_NAME_CREATED_WEBHOOK_ID = "createdWebhookId";
  @SerializedName(SERIALIZED_NAME_CREATED_WEBHOOK_ID)
  private Long createdWebhookId;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<String> errors = null;


  public RegisteredWebhook createdWebhookId(Long createdWebhookId) {
    
    this.createdWebhookId = createdWebhookId;
    return this;
  }

   /**
   * The ID of the webhook. Returned if the webhook is created.
   * @return createdWebhookId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the webhook. Returned if the webhook is created.")

  public Long getCreatedWebhookId() {
    return createdWebhookId;
  }


  public void setCreatedWebhookId(Long createdWebhookId) {
    this.createdWebhookId = createdWebhookId;
  }


  public RegisteredWebhook errors(List<String> errors) {
    
    this.errors = errors;
    return this;
  }

  public RegisteredWebhook addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Error messages specifying why the webhook creation failed.
   * @return errors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Error messages specifying why the webhook creation failed.")

  public List<String> getErrors() {
    return errors;
  }


  public void setErrors(List<String> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisteredWebhook registeredWebhook = (RegisteredWebhook) o;
    return Objects.equals(this.createdWebhookId, registeredWebhook.createdWebhookId) &&
        Objects.equals(this.errors, registeredWebhook.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdWebhookId, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisteredWebhook {\n");
    sb.append("    createdWebhookId: ").append(toIndentedString(createdWebhookId)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

