/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The IDs of the screens for the screen types of the screen scheme.
 */
@ApiModel(description = "The IDs of the screens for the screen types of the screen scheme.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-17T17:45:56.601554Z[Etc/UTC]")
public class ScreenTypes {
  public static final String SERIALIZED_NAME_EDIT = "edit";
  @SerializedName(SERIALIZED_NAME_EDIT)
  private Long edit;

  public static final String SERIALIZED_NAME_CREATE = "create";
  @SerializedName(SERIALIZED_NAME_CREATE)
  private Long create;

  public static final String SERIALIZED_NAME_VIEW = "view";
  @SerializedName(SERIALIZED_NAME_VIEW)
  private Long view;

  public static final String SERIALIZED_NAME_DEFAULT = "default";
  @SerializedName(SERIALIZED_NAME_DEFAULT)
  private Long _default;


  public ScreenTypes edit(Long edit) {
    
    this.edit = edit;
    return this;
  }

   /**
   * The ID of the edit screen.
   * @return edit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the edit screen.")

  public Long getEdit() {
    return edit;
  }


  public void setEdit(Long edit) {
    this.edit = edit;
  }


  public ScreenTypes create(Long create) {
    
    this.create = create;
    return this;
  }

   /**
   * The ID of the create screen.
   * @return create
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the create screen.")

  public Long getCreate() {
    return create;
  }


  public void setCreate(Long create) {
    this.create = create;
  }


  public ScreenTypes view(Long view) {
    
    this.view = view;
    return this;
  }

   /**
   * The ID of the view screen.
   * @return view
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the view screen.")

  public Long getView() {
    return view;
  }


  public void setView(Long view) {
    this.view = view;
  }


  public ScreenTypes _default(Long _default) {
    
    this._default = _default;
    return this;
  }

   /**
   * The ID of the default screen. Required when creating a screen scheme.
   * @return _default
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the default screen. Required when creating a screen scheme.")

  public Long getDefault() {
    return _default;
  }


  public void setDefault(Long _default) {
    this._default = _default;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScreenTypes screenTypes = (ScreenTypes) o;
    return Objects.equals(this.edit, screenTypes.edit) &&
        Objects.equals(this.create, screenTypes.create) &&
        Objects.equals(this.view, screenTypes.view) &&
        Objects.equals(this._default, screenTypes._default);
  }

  @Override
  public int hashCode() {
    return Objects.hash(edit, create, view, _default);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScreenTypes {\n");
    sb.append("    edit: ").append(toIndentedString(edit)).append("\n");
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    view: ").append(toIndentedString(view)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

