/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * List of custom fields using the version.
 */
@ApiModel(description = "List of custom fields using the version.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-17T17:45:56.601554Z[Etc/UTC]")
public class VersionUsageInCustomField {
  public static final String SERIALIZED_NAME_FIELD_NAME = "fieldName";
  @SerializedName(SERIALIZED_NAME_FIELD_NAME)
  private String fieldName;

  public static final String SERIALIZED_NAME_CUSTOM_FIELD_ID = "customFieldId";
  @SerializedName(SERIALIZED_NAME_CUSTOM_FIELD_ID)
  private Long customFieldId;

  public static final String SERIALIZED_NAME_ISSUE_COUNT_WITH_VERSION_IN_CUSTOM_FIELD = "issueCountWithVersionInCustomField";
  @SerializedName(SERIALIZED_NAME_ISSUE_COUNT_WITH_VERSION_IN_CUSTOM_FIELD)
  private Long issueCountWithVersionInCustomField;


   /**
   * The name of the custom field.
   * @return fieldName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the custom field.")

  public String getFieldName() {
    return fieldName;
  }




   /**
   * The ID of the custom field.
   * @return customFieldId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the custom field.")

  public Long getCustomFieldId() {
    return customFieldId;
  }




   /**
   * Count of the issues where the custom field contains the version.
   * @return issueCountWithVersionInCustomField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of the issues where the custom field contains the version.")

  public Long getIssueCountWithVersionInCustomField() {
    return issueCountWithVersionInCustomField;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionUsageInCustomField versionUsageInCustomField = (VersionUsageInCustomField) o;
    return Objects.equals(this.fieldName, versionUsageInCustomField.fieldName) &&
        Objects.equals(this.customFieldId, versionUsageInCustomField.customFieldId) &&
        Objects.equals(this.issueCountWithVersionInCustomField, versionUsageInCustomField.issueCountWithVersionInCustomField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldName, customFieldId, issueCountWithVersionInCustomField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionUsageInCustomField {\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    customFieldId: ").append(toIndentedString(customFieldId)).append("\n");
    sb.append("    issueCountWithVersionInCustomField: ").append(toIndentedString(issueCountWithVersionInCustomField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

