/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.datengaertnerei.jira.rest.client.model.UserDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The details of watchers on an issue.
 */
@ApiModel(description = "The details of watchers on an issue.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-17T17:45:56.601554Z[Etc/UTC]")
public class Watchers {
  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  private String self;

  public static final String SERIALIZED_NAME_IS_WATCHING = "isWatching";
  @SerializedName(SERIALIZED_NAME_IS_WATCHING)
  private Boolean isWatching;

  public static final String SERIALIZED_NAME_WATCH_COUNT = "watchCount";
  @SerializedName(SERIALIZED_NAME_WATCH_COUNT)
  private Integer watchCount;

  public static final String SERIALIZED_NAME_WATCHERS = "watchers";
  @SerializedName(SERIALIZED_NAME_WATCHERS)
  private List<UserDetails> watchers = null;


   /**
   * The URL of these issue watcher details.
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL of these issue watcher details.")

  public String getSelf() {
    return self;
  }




   /**
   * Whether the calling user is watching this issue.
   * @return isWatching
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the calling user is watching this issue.")

  public Boolean getIsWatching() {
    return isWatching;
  }




   /**
   * The number of users watching this issue.
   * @return watchCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of users watching this issue.")

  public Integer getWatchCount() {
    return watchCount;
  }




   /**
   * Details of the users watching this issue.
   * @return watchers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details of the users watching this issue.")

  public List<UserDetails> getWatchers() {
    return watchers;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Watchers watchers = (Watchers) o;
    return Objects.equals(this.self, watchers.self) &&
        Objects.equals(this.isWatching, watchers.isWatching) &&
        Objects.equals(this.watchCount, watchers.watchCount) &&
        Objects.equals(this.watchers, watchers.watchers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, isWatching, watchCount, watchers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Watchers {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    isWatching: ").append(toIndentedString(isWatching)).append("\n");
    sb.append("    watchCount: ").append(toIndentedString(watchCount)).append("\n");
    sb.append("    watchers: ").append(toIndentedString(watchers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

