/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.datengaertnerei.jira.rest.client.model.CrateWorkflowStatusDetails;
import com.datengaertnerei.jira.rest.client.model.CreateWorkflowTransitionDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateWorkflowDetails
 */
public class CreateWorkflowDetailsTest {
    private final CreateWorkflowDetails model = new CreateWorkflowDetails();

    /**
     * Model tests for CreateWorkflowDetails
     */
    @Test
    public void testCreateWorkflowDetails() {
        // TODO: test CreateWorkflowDetails
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'transitions'
     */
    @Test
    public void transitionsTest() {
        // TODO: test transitions
    }

    /**
     * Test the property 'statuses'
     */
    @Test
    public void statusesTest() {
        // TODO: test statuses
    }

}
