/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.datengaertnerei.jira.rest.client.model.EntityProperty;
import com.datengaertnerei.jira.rest.client.model.FieldUpdateOperation;
import com.datengaertnerei.jira.rest.client.model.HistoryMetadata;
import com.datengaertnerei.jira.rest.client.model.IssueTransition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IssueUpdateDetails
 */
public class IssueUpdateDetailsTest {
    private final IssueUpdateDetails model = new IssueUpdateDetails();

    /**
     * Model tests for IssueUpdateDetails
     */
    @Test
    public void testIssueUpdateDetails() {
        // TODO: test IssueUpdateDetails
    }

    /**
     * Test the property 'transition'
     */
    @Test
    public void transitionTest() {
        // TODO: test transition
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'update'
     */
    @Test
    public void updateTest() {
        // TODO: test update
    }

    /**
     * Test the property 'historyMetadata'
     */
    @Test
    public void historyMetadataTest() {
        // TODO: test historyMetadata
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

}
