/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.datengaertnerei.jira.rest.client.model.IssueTypeScreenSchemeMapping;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IssueTypeScreenSchemeMappingDetails
 */
public class IssueTypeScreenSchemeMappingDetailsTest {
    private final IssueTypeScreenSchemeMappingDetails model = new IssueTypeScreenSchemeMappingDetails();

    /**
     * Model tests for IssueTypeScreenSchemeMappingDetails
     */
    @Test
    public void testIssueTypeScreenSchemeMappingDetails() {
        // TODO: test IssueTypeScreenSchemeMappingDetails
    }

    /**
     * Test the property 'issueTypeMappings'
     */
    @Test
    public void issueTypeMappingsTest() {
        // TODO: test issueTypeMappings
    }

}
