/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IssueTypeSchemeProjectAssociation
 */
public class IssueTypeSchemeProjectAssociationTest {
    private final IssueTypeSchemeProjectAssociation model = new IssueTypeSchemeProjectAssociation();

    /**
     * Model tests for IssueTypeSchemeProjectAssociation
     */
    @Test
    public void testIssueTypeSchemeProjectAssociation() {
        // TODO: test IssueTypeSchemeProjectAssociation
    }

    /**
     * Test the property 'issueTypeSchemeId'
     */
    @Test
    public void issueTypeSchemeIdTest() {
        // TODO: test issueTypeSchemeId
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

}
