/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JQLQueryWithUnknownUsers
 */
public class JQLQueryWithUnknownUsersTest {
    private final JQLQueryWithUnknownUsers model = new JQLQueryWithUnknownUsers();

    /**
     * Model tests for JQLQueryWithUnknownUsers
     */
    @Test
    public void testJQLQueryWithUnknownUsers() {
        // TODO: test JQLQueryWithUnknownUsers
    }

    /**
     * Test the property 'originalQuery'
     */
    @Test
    public void originalQueryTest() {
        // TODO: test originalQuery
    }

    /**
     * Test the property 'convertedQuery'
     */
    @Test
    public void convertedQueryTest() {
        // TODO: test convertedQuery
    }

}
