/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.datengaertnerei.jira.rest.client.model.WorkflowTransitionRules;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PageBeanWorkflowTransitionRules
 */
public class PageBeanWorkflowTransitionRulesTest {
    private final PageBeanWorkflowTransitionRules model = new PageBeanWorkflowTransitionRules();

    /**
     * Model tests for PageBeanWorkflowTransitionRules
     */
    @Test
    public void testPageBeanWorkflowTransitionRules() {
        // TODO: test PageBeanWorkflowTransitionRules
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'nextPage'
     */
    @Test
    public void nextPageTest() {
        // TODO: test nextPage
    }

    /**
     * Test the property 'maxResults'
     */
    @Test
    public void maxResultsTest() {
        // TODO: test maxResults
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    public void startAtTest() {
        // TODO: test startAt
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'isLast'
     */
    @Test
    public void isLastTest() {
        // TODO: test isLast
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
