/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProjectInsight
 */
public class ProjectInsightTest {
    private final ProjectInsight model = new ProjectInsight();

    /**
     * Model tests for ProjectInsight
     */
    @Test
    public void testProjectInsight() {
        // TODO: test ProjectInsight
    }

    /**
     * Test the property 'totalIssueCount'
     */
    @Test
    public void totalIssueCountTest() {
        // TODO: test totalIssueCount
    }

    /**
     * Test the property 'lastIssueUpdateTime'
     */
    @Test
    public void lastIssueUpdateTimeTest() {
        // TODO: test lastIssueUpdateTime
    }

}
