/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.datengaertnerei.jira.rest.client.model.Application;
import com.datengaertnerei.jira.rest.client.model.RemoteObject;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RemoteIssueLinkRequest
 */
public class RemoteIssueLinkRequestTest {
    private final RemoteIssueLinkRequest model = new RemoteIssueLinkRequest();

    /**
     * Model tests for RemoteIssueLinkRequest
     */
    @Test
    public void testRemoteIssueLinkRequest() {
        // TODO: test RemoteIssueLinkRequest
    }

    /**
     * Test the property 'globalId'
     */
    @Test
    public void globalIdTest() {
        // TODO: test globalId
    }

    /**
     * Test the property 'application'
     */
    @Test
    public void applicationTest() {
        // TODO: test application
    }

    /**
     * Test the property 'relationship'
     */
    @Test
    public void relationshipTest() {
        // TODO: test relationship
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

}
