/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.datengaertnerei.jira.rest.client.model.HealthCheckResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ServerInformation
 */
public class ServerInformationTest {
    private final ServerInformation model = new ServerInformation();

    /**
     * Model tests for ServerInformation
     */
    @Test
    public void testServerInformation() {
        // TODO: test ServerInformation
    }

    /**
     * Test the property 'baseUrl'
     */
    @Test
    public void baseUrlTest() {
        // TODO: test baseUrl
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'versionNumbers'
     */
    @Test
    public void versionNumbersTest() {
        // TODO: test versionNumbers
    }

    /**
     * Test the property 'deploymentType'
     */
    @Test
    public void deploymentTypeTest() {
        // TODO: test deploymentType
    }

    /**
     * Test the property 'buildNumber'
     */
    @Test
    public void buildNumberTest() {
        // TODO: test buildNumber
    }

    /**
     * Test the property 'buildDate'
     */
    @Test
    public void buildDateTest() {
        // TODO: test buildDate
    }

    /**
     * Test the property 'serverTime'
     */
    @Test
    public void serverTimeTest() {
        // TODO: test serverTime
    }

    /**
     * Test the property 'scmInfo'
     */
    @Test
    public void scmInfoTest() {
        // TODO: test scmInfo
    }

    /**
     * Test the property 'serverTitle'
     */
    @Test
    public void serverTitleTest() {
        // TODO: test serverTitle
    }

    /**
     * Test the property 'healthChecks'
     */
    @Test
    public void healthChecksTest() {
        // TODO: test healthChecks
    }

}
