/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datengaertnerei.jira.rest.client.model;

import com.datengaertnerei.jira.rest.client.model.WorkflowId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkflowTransitionRulesUpdateErrorDetails
 */
public class WorkflowTransitionRulesUpdateErrorDetailsTest {
    private final WorkflowTransitionRulesUpdateErrorDetails model = new WorkflowTransitionRulesUpdateErrorDetails();

    /**
     * Model tests for WorkflowTransitionRulesUpdateErrorDetails
     */
    @Test
    public void testWorkflowTransitionRulesUpdateErrorDetails() {
        // TODO: test WorkflowTransitionRulesUpdateErrorDetails
    }

    /**
     * Test the property 'workflowId'
     */
    @Test
    public void workflowIdTest() {
        // TODO: test workflowId
    }

    /**
     * Test the property 'ruleUpdateErrors'
     */
    @Test
    public void ruleUpdateErrorsTest() {
        // TODO: test ruleUpdateErrors
    }

    /**
     * Test the property 'updateErrors'
     */
    @Test
    public void updateErrorsTest() {
        // TODO: test updateErrors
    }

}
